services:
  app-memory:
    build: .
    ports:
      - "8080:8080"
    environment:
      STORAGE_TYPE: memory
      PORT: "8080"
      MAX_RETRIES: "3"

  app-postgres:
    build: .
    ports:
      - "8081:8081"
    environment:
      STORAGE_TYPE: postgres
      PORT: "8081"
      DATABASE_URL: postgres://user:password@db:5432/shortener_db?sslmode=disable
      MAX_RETRIES: "3"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432"
    volumes:
      - ./internal/repository/postgres/migrations.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shortener_db"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
